server.port=8080
spring.application.name=vulnerasolve-network-scanner

# Configuración del motor de escaneo concurrente de red local
scanner.thread-pool-size=30
scanner.ping-timeout-ms=400
scanner.port-timeout-ms=250
